### ISSUE TITLE
FSUSER functions don't work with latest ctrulib

### ISSUE THREAD

**Issue by Wolfvak** [joel16/Cyanogen3DS#3]
ctrulib commit https://github.com/smealum/ctrulib/commit/cf91be5041cc7f9f816021d5ca5af5b7338fd89a breaks file system related functions, thereby making compilation impossible for those running a ctrulib version newer than that.

**Comment by joel16** [comment]
Fixed https://github.com/joel16/Cyanogen3DS/commit/6a245b66dd1e0bd256b82d10fd673482b66fbe9f

**Comment by Wolfvak** [comment]
Thanks.
