### ISSUE TITLE
Freeze and crash when clicking on 'Game' Icon

### ISSUE THREAD

**Issue by OTFree** [joel16/Cyanogen3DS#6]
Hey, me again! Not sure if the game icon is intended to boot to the game in your slot, but when I clicked on it, the GUI froze, and seconds later, resulted in a black screen crash.

**Comment by joel16** [comment]
Yes I was testing that, wasn't sure if it work but I guess it doesn't haha. It was just there for testing purposes. I'll remove it until I find a fix.

**Comment by joel16** [comment]
Closing this because this was only used for testing purposes and won't be in stable releases.
