### ISSUE TITLE
[Feature Request] Installable .Cia file?

### ISSUE THREAD

**Issue by OTFree** [joel16/Cyanogen3DS#7]
I'm more than comfortable with booting from HBLauncher for the time being, but it would be nice to see a .Cia come about in a future, more stable release for CFW users such as myself :D

**Comment by joel16** [comment]
Hmm if I recall @Wolfvak tried it once and reported that it didn't work properly or something.  I've never tried it myself even though I'm also a cfw user haha. I'll try it later tonight and see how it goes.

**Comment by OTFree** [comment]
Awesome! Thank you again for the quick and kind replies :) Looking forward
to future endeavors, keep up the great work!

**Comment by Wolfvak** [comment]
It technically works, but exiting the app is a pain (as in, it doesn't work. At all)
Maybe it's been fixed with newer versions, all it needs is to be in a loop which calls aptMainLoop(), which is the one handling Home button, and exiting and resuming accordingly.

**Comment by joel16** [comment]
CIA builds will now follow. https://github.com/joel16/Cyanogen3DS/commit/a79652db2f8faaff94cd70f400117b76f844cd17
