### ISSUE TITLE
Compilation fails on screenshot.h

### ISSUE THREAD

**Issue by nobody231** [joel16/Cyanogen3DS#8]
When trying to compile with the latest commit, I get the following error:
"In file included from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.c:9:0:
f:/3DS_Homebrew/Cyanogen3DS-master/source/screenshot.h:6:17: fatal error: png.h: No such file or directory"
It seems that files that don't exist are being referenced. Should I simply delete the nonexistent references? This was compiled from the latest commit.

**Comment by joel16** [comment]
You're probably missing portlibs. You need it installed onto devkitARM.
As you can see here(https://travis-ci.org/joel16/Cyanogen3DS) the latest nightly build compiled successfully. And it was done about 18 hours ago.

You can get portlibs here: https://github.com/devkitPro/3ds_portlibs

**Comment by nobody231** [comment]
Well, this is what I get for trying to jump straight into compiling 3DS homebrew without reading anything more than "make" and "install devkitARM". I'll go do this now.

**Comment by joel16** [comment]
Hmm, well in your c:/devkitPro folder, do you see a folder called portlibs?

**Comment by nobody231** [comment]
....No. I guess I don't know how to install libraries, I'll go look it up quick.

**Comment by joel16** [comment]
https://github.com/xerpi/3ds_portlibs/releases

Move the portlibs folder into the c:/devkitPro folder.

**Comment by joel16** [comment]
Just so you know, Cyanogen3DS is broken at the moment. It's a problem with sf2dlib and citro3d. Something I can't seem to fix no matter what I try.

**Comment by nobody231** [comment]
Broken? Darn. I wish I knew something about programming beyond generic single-purpose programs.

**Comment by joel16** [comment]
Yeah there's a problem with the libraries, and for some weird reason it hasn't been working properly since they made some major GPU changes.

**Comment by nobody231** [comment]
Well, I guess I'll wait for something to get fixed. 

In the meantime, I got a little annoying error:
"f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c: In function 'openSdArchive':
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:27:2: error: too many arguments to function 'FSUSER_OpenArchive'
  FSUSER_OpenArchive(&sdmcArchive, ARCHIVE_SDMC, fsMakePath(PATH_EMPTY, ""));
  ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:369:8: note: declared here
 Result FSUSER_OpenArchive(FS_Archive* archive);
        ^
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c: In function 'closeSdArchive':
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:32:22: error: incompatible type for argument 1 of 'FSUSER_CloseArchive'
  FSUSER_CloseArchive(sdmcArchive);
                      ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:386:8: note: expected 'FS_Archive * {aka struct <anonymous> *}' but argument is of type 'FS_Archive {aka struct <anonymous>}'
 Result FSUSER_CloseArchive(FS_Archive* archive);
        ^
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c: In function 'openFileHandle':
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:58:38: error: incompatible type for argument 2 of 'FSUSER_OpenFile'
     if (FSUSER_OpenFile(&fileHandle, ARCHIVE_SDMC, filePath, FS_OPEN_READ & 3, 0))
                                      ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:289:8: note: expected 'FS_Archive {aka struct <anonymous>}' but argument is of type 'int'
 Result FSUSER_OpenFile(Handle* out, FS_Archive archive, FS_Path path, u32 openFlags, u32 attributes);
        ^
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:60:38: error: incompatible type for argument 2 of 'FSUSER_OpenFile'
         FSUSER_OpenFile(&fileHandle, ARCHIVE_SDMC, filePath, FS_OPEN_READ, 0);
                                      ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:289:8: note: expected 'FS_Archive {aka struct <anonymous>}' but argument is of type 'int'
 Result FSUSER_OpenFile(Handle* out, FS_Archive archive, FS_Path path, u32 openFlags, u32 attributes);
        ^
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c: In function 'loadFiles':
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:158:2: error: too many arguments to function 'FSUSER_OpenArchive'
  FSUSER_OpenArchive(&sdmcArchive, ARCHIVE_SDMC, fsMakePath(PATH_EMPTY, ""));
  ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:369:8: note: declared here
 Result FSUSER_OpenArchive(FS_Archive* archive);
        ^
f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:223:22: error: incompatible type for argument 1 of 'FSUSER_CloseArchive'
  FSUSER_CloseArchive(sdmcArchive);
                      ^
In file included from c:/devkitPro/libctru/include/3ds.h:37:0,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/appDrawer.h:3,
                 from f:/3DS_Homebrew/Cyanogen3DS-master/source/fileManager.c:1:
c:/devkitPro/libctru/include/3ds/services/fs.h:386:8: note: expected 'FS_Archive * {aka struct <anonymous> *}' but argument is of type 'FS_Archive {aka struct <anonymous>}'
 Result FSUSER_CloseArchive(FS_Archive* archive);
        ^
make[1]: *** [fileManager.o] Error 1
make: *** [build] Error 2"
I don't quite know what's going on here. Sorry for the massive wall of text, but I don't know how to shrink that down.

**Comment by joel16** [comment]
You need the latest version of CTRULIB
https://github.com/smealum/ctrulib
Download the source code. Press make and let it compile.
After it has compiled successfully. Copy the lib and include folder to your C:/devkitpro/libctru.
Replace any existing files. After you've done all this, try compiling Cyanogen3DS.

**Comment by nobody231** [comment]
Ugh, the errors don't end. I'm beginning to think that all of this could be solved by actually _reading_ a guide on compilation stuff. 
"linking Cyanogen3DS-master.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lsftd
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lsfil
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lsf2d
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/f/3DS_Homebrew/Cyanogen3DS-master/Cyanogen3DS-master.elf] Error 1
make: *** [build] Error 2"
I have no idea what it wants to link. It seems that the files have been compiled, unless if more compilations happen after linking.

**Comment by joel16** [comment]
You need sf2d sflib and sftd. Once you compile those, you move the lib and include folder from each of the 3 libaries into the C:/devkitpro/libctru/ folder.

SF2D lib: https://github.com/xerpi/sf2dlib
SFTD lib: https://github.com/xerpi/sftdlib
SFIL lib: https://github.com/xerpi/sfillib

**Comment by nobody231** [comment]
... why didn't I think of that. I seriously feel like a dumbass, not installing all of the 3DS libraries beforehand. Could you link me to other 3DS libraries? I don't know them all, as I'm not familiar with 3DS development.

**Comment by joel16** [comment]
Oh yeah do the same with citro3d. 
Download it, compile it and move to devkitPro/libctru. Make sure it's named citro3d.a and not citro3d-master.a (In the lib folder afyer compiling)

**Comment by nobody231** [comment]
Phew, I got it all to work! Thanks for the help, and sorry I took so long.

**Comment by joel16** [comment]
Haha yeah no problem. I'll close this issue now. Feel free to leave any comments here if you have any.
